export const LINEAGE_TEMPLATE_FIELDS = [
  'name',
  'database',
  'type',
  'schema',
  'owner',
  'steward',
  'domain_manager',
  'custodian',
  'sensitivity',
  'tags',
  'depends_on',
  'reads_from',
  'writes_to',
  'calls',
  'called_by',
  'row_count',
  'size_kb',
  'column_count',
  'index_count',
  'check_constraint_count',
  'edge_count',
  'edge_quality_score',
  'lineage_confidence',
  'lineage_strategy',
  'lineage_pattern_class',
  'lineage_source',
  'lineage_source_path',
  'lineage_evidence_hash',
  'extraction_warnings',
  'extracted_at',
  'last_updated',
];

export const LINEAGE_TEMPLATE_DEFAULTS = {
  owner: 'Data Team',
  steward: 'To be assigned',
  domain_manager: 'To be assigned',
  custodian: 'To be assigned',
  sensitivity: 'internal',
  tags: [],
  depends_on: [],
  reads_from: [],
  writes_to: [],
  calls: [],
  called_by: [],
  row_count: 0,
  size_kb: 0,
  column_count: 0,
  index_count: 0,
  check_constraint_count: 0,
  edge_count: 0,
  edge_quality_score: 0,
  lineage_confidence: 'unknown',
  lineage_strategy: 'unknown',
  lineage_pattern_class: 'unknown',
  lineage_source: 'unknown',
  lineage_source_path: 'unknown',
  lineage_evidence_hash: 'unknown',
  extraction_warnings: [],
  extracted_at: '',
  last_updated: '',
};

export function getLineageTemplateDefaults() {
  return { ...LINEAGE_TEMPLATE_DEFAULTS };
}
